language: node_js
node_js:
  - "12.16.2"
install: yarn
script:
  - yarn build
  - echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
  - docker build -t alantoa/my-blog:tagname .  
  - docker push alantoa/my-blog:tagname